ルーム作成オプション、およびルーム名の追加
dayaman/roomCreator pull request #1
Opened 2020-08-29 03:17 UTC by pekko1215

以下のオプション実装の提案です。
ルーム作成時、後方に付与することで有効になる仕様です。

## WORLDS_EDGE:
   > -w  --worlds_edge
   > 命名テーブルをWorldsEdge基準に設定

## KINGS_CANYON:
   > -k  --kings_canyon
   > 命名テーブルをKingsCanyon基準に設定

## WEAPONS:
   > -p  --weapons
   > 命名テーブルをWeapons基準に設定

## HELP:
   > -h  --help
   > ヘルプを表示

2020-08-29 15:25 UTC, dayaman commented
気分に合わせてカテゴリ名を選べるのいいですね。

2020-09-12 15:07 UTC, dayaman requested changes

2020-09-12 15:07 UTC, dayaman commented on main.py
> +    message = ""
ここをはじめとして、ダブルクウォートになっている部分がいくつかあるので、シングルクウォートに揃えていただきたいです。

2020-09-13 05:19 UTC, pekko1215 commented on main.py
> +    message = ""
修正しました。確認よろしくお願いします。

2020-09-13 05:22 UTC, merged